In [1]:
import os 
os.chdir("../")
!pwd

/d/DA_workspace/price_prediction/src

In [2]:
import pandas as pd
import numpy as np
from classifier.Mylib import myfuncs
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.base import BaseEstimator, TransformerMixin

Doc du lieu

In [3]:
df = myfuncs.load_python_object("../artifacts/data_ingestion/test_data.pkl")

df.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,1562,1,0.7,0,0,0,55,0.1,140,8,...,1032,1776,2096,15,3,3,0,0,0,2
1,1354,1,0.7,1,3,1,26,0.5,136,4,...,297,918,2090,5,1,13,1,1,0,1
2,1058,0,1.5,0,2,0,19,0.4,166,4,...,493,1247,418,9,7,16,0,0,1,0
3,1993,1,0.5,0,10,1,27,0.3,147,8,...,150,510,2437,14,0,9,1,0,0,2
4,1786,0,0.5,0,9,1,58,0.7,161,7,...,231,1671,2764,9,3,7,1,1,1,3

Kich thuoc

In [4]:
df.shape

(200, 21)

Ti le missing cac cot

In [5]:
df.isnull().mean() * 100

battery_power    0.0
blue             0.0
clock_speed      0.0
dual_sim         0.0
fc               0.0
four_g           0.0
int_memory       0.0
m_dep            0.0
mobile_wt        0.0
n_cores          0.0
pc               0.0
px_height        0.0
px_width         0.0
ram              0.0
sc_h             0.0
sc_w             0.0
talk_time        0.0
three_g          0.0
touch_screen     0.0
wifi             0.0
price_range      0.0
dtype: float64

Khong xoa cot nao het !

Kich thuoc con lai

In [6]:
df.shape

(200, 21)

Doi ten cot

In [7]:
df.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='object')

In [ ]:
rename_dict = {
    "blue": "do_have_bluetooth",
    "clock_speed": "microprocessor_handling_speed",
    "dual_sim": "do_have_dual_sim",
    "fc": "megapixels_front_cam",
    "four_g": "do_have_four_g",
    "m_dep": "mobile_depth",
    "pc": "megapixels_primary_cam",
    "ram": "ram_memory",
    "sc_h": "sc_height",
    "sc_w": "sc_width",
    "talk_time": "longest_charging_time",
    "three_g": "do_have_three_g",
    "touch_screen": "do_have_touch_screen",
    "wifi": "do_have_wifi",
}


df = df.rename(columns=rename_dict)

df.head()

,battery_power,do_have_bluetooth,microprocessor_handling_speed,do_have_dual_sim,megapixels_front_cam,do_have_four_g,int_memory,mobile_depth,mobile_wt,n_cores,...,px_height,px_width,ram_memory,sc_height,sc_width,longest_charging_time,do_have_three_g,do_have_touch_screen,do_have_wifi,price_range
0,1562,1,0.7,0,0,0,55,0.1,140,8,...,1032,1776,2096,15,3,3,0,0,0,2
1,1354,1,0.7,1,3,1,26,0.5,136,4,...,297,918,2090,5,1,13,1,1,0,1
2,1058,0,1.5,0,2,0,19,0.4,166,4,...,493,1247,418,9,7,16,0,0,1,0
3,1993,1,0.5,0,10,1,27,0.3,147,8,...,150,510,2437,14,0,9,1,0,0,2
4,1786,0,0.5,0,9,1,58,0.7,161,7,...,231,1671,2764,9,3,7,1,1,1,3

Chuyen cac cot numeric va categorical ve dung vi tri

In [9]:
df.columns

Index(['battery_power', 'do_have_bluetooth', 'microprocessor_handling_speed',
       'do_have_dual_sim', 'megapixels_front_cam', 'do_have_four_g',
       'int_memory', 'mobile_depth', 'mobile_wt', 'n_cores',
       'megapixels_primary_cam', 'px_height', 'px_width', 'ram_memory',
       'sc_height', 'sc_width', 'longest_charging_time', 'do_have_three_g',
       'do_have_touch_screen', 'do_have_wifi', 'price_range'],
      dtype='object')

In [10]:
numeric_cols = [
    "battery_power",
    "microprocessor_handling_speed",
    "megapixels_front_cam",
    "int_memory",
    "mobile_depth",
    "mobile_wt",
    "n_cores",
    "megapixels_primary_cam",
    "px_height",
    "px_width",
    "ram_memory",
    "sc_height",
    "sc_width",
    "longest_charging_time",
]
cat_cols = [
    "do_have_bluetooth",
    "do_have_dual_sim",
    "do_have_four_g",
    "do_have_three_g",
    "do_have_touch_screen",
    "do_have_wifi",
]

target_col = "price_range"

df = df[numeric_cols + cat_cols + [target_col]]

df.head()

,battery_power,microprocessor_handling_speed,megapixels_front_cam,int_memory,mobile_depth,mobile_wt,n_cores,megapixels_primary_cam,px_height,px_width,...,sc_height,sc_width,longest_charging_time,do_have_bluetooth,do_have_dual_sim,do_have_four_g,do_have_three_g,do_have_touch_screen,do_have_wifi,price_range
0,1562,0.7,0,55,0.1,140,8,1,1032,1776,...,15,3,3,1,0,0,0,0,0,2
1,1354,0.7,3,26,0.5,136,4,6,297,918,...,5,1,13,1,1,1,1,1,0,1
2,1058,1.5,2,19,0.4,166,4,14,493,1247,...,9,7,16,0,0,0,0,0,1,0
3,1993,0.5,10,27,0.3,147,8,11,150,510,...,14,0,9,1,0,1,1,0,0,2
4,1786,0.5,9,58,0.7,161,7,10,231,1671,...,9,3,7,0,0,1,1,1,1,3

Kiá»ƒm tra cÃ¡c cá»™t binary thÃ¬ kiá»ƒm tra chá»‰ cÃ³ 2 giÃ¡ trá»‹ 1 vÃ  0 thÃ´i

Kiem tra kieu du lieu cac cot

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   battery_power                  200 non-null    int64
 1   microprocessor_handling_speed  200 non-null    float64
 2   megapixels_front_cam           200 non-null    int64
 3   int_memory                     200 non-null    int64
 4   mobile_depth                   200 non-null    float64
 5   mobile_wt                      200 non-null    int64
 6   n_cores                        200 non-null    int64
 7   megapixels_primary_cam         200 non-null    int64
 8   px_height                      200 non-null    int64
 9   px_width                       200 non-null    int64
 10  ram_memory                     200 non-null    int64
 11  sc_height                      200 non-null    int64
 12  sc_width                       200 non-null    int64
 13  longest_charging_time          200 non-null    int64
 14  do_have_bluetooth              200 non-null    int64
 15  do_have_dual_sim               200 non-null    int64
 16  do_have_four_g                 200 non-null    int64
 17  do_have_three_g                200 non-null    int64
 18  do_have_touch_screen           200 non-null    int64
 19  do_have_wifi                   200 non-null    int64
 20  price_range                    200 non-null    int64
dtypes: float64(2), int64(19)
memory usage: 32.9 KB

Dung het !!

Kiem tra noi dung cac cot

Cot numeric

In [ ]:
df[numeric_cols].describe().loc[["min", "max", "mean"]]

,battery_power,microprocessor_handling_speed,megapixels_front_cam,int_memory,mobile_depth,mobile_wt,n_cores,megapixels_primary_cam,px_height,px_width,ram_memory,sc_height,sc_width,longest_charging_time
min,501.00,0.5000,0.00,2.000,0.1000,80.00,1.000,0.000,0.0,506.00,265.00,5.000,0.00,2.000
max,1996.00,3.0000,18.00,64.000,1.0000,200.00,8.000,20.000,1899.0,1988.00,3990.00,19.000,16.00,20.000
mean,1243.95,1.5665,4.21,32.445,0.4865,142.63,4.435,10.085,648.8,1291.87,2118.16,12.555,5.56,11.655

Cot binary

In [13]:
binary_cols = [
    "do_have_bluetooth",
    "do_have_dual_sim",
    "do_have_four_g",
    "do_have_three_g",
    "do_have_touch_screen",
    "do_have_wifi",
]

df[binary_cols].nunique()

do_have_bluetooth       2
do_have_dual_sim        2
do_have_four_g          2
do_have_three_g         2
do_have_touch_screen    2
do_have_wifi            2
dtype: int64

Cot cat

In [14]:
cat_type_cols = ["price_range"]

for col in cat_type_cols:
    print(f"{col} -> {df[col].unique().tolist()}")

price_range -> [2, 1, 0, 3]

In [15]:
df["price_range"] = df["price_range"].replace(
    {
        0: "low_cost",
        1: "medium_cost",
        2: "high_cost",
        3: "very_high_cost",
    }
)

In [16]:
cat_type_cols = ["price_range"]

for col in cat_type_cols:
    print(f"{col} -> {df[col].unique().tolist()}")

price_range -> ['high_cost', 'medium_cost', 'low_cost', 'very_high_cost']

Fill missing value

In [ ]:
cat_cols = binary_cols + cat_type_cols

preprocessor = myfuncs.load_python_object(
    "../artifacts/data_correction/missing_value_handler.pkl"
)

df_filled = preprocessor.transform(df)
df_filled = pd.DataFrame(df_filled, columns=numeric_cols + cat_cols)

df_filled.head()

,battery_power,microprocessor_handling_speed,megapixels_front_cam,int_memory,mobile_depth,mobile_wt,n_cores,megapixels_primary_cam,px_height,px_width,...,sc_height,sc_width,longest_charging_time,do_have_bluetooth,do_have_dual_sim,do_have_four_g,do_have_three_g,do_have_touch_screen,do_have_wifi,price_range
0,1562.0,0.7,0.0,55.0,0.1,140.0,8.0,1.0,1032.0,1776.0,...,15.0,3.0,3.0,1,0,0,0,0,0,high_cost
1,1354.0,0.7,3.0,26.0,0.5,136.0,4.0,6.0,297.0,918.0,...,5.0,1.0,13.0,1,1,1,1,1,0,medium_cost
2,1058.0,1.5,2.0,19.0,0.4,166.0,4.0,14.0,493.0,1247.0,...,9.0,7.0,16.0,0,0,0,0,0,1,low_cost
3,1993.0,0.5,10.0,27.0,0.3,147.0,8.0,11.0,150.0,510.0,...,14.0,0.0,9.0,1,0,1,1,0,0,high_cost
4,1786.0,0.5,9.0,58.0,0.7,161.0,7.0,10.0,231.0,1671.0,...,9.0,3.0,7.0,0,0,1,1,1,1,very_high_cost

Chuyen doi ve dung kieu du lieu

In [18]:
df_filled[numeric_cols + binary_cols] = df_filled[numeric_cols + binary_cols].astype(
    "float"
)
df_filled[cat_type_cols] = df_filled[cat_type_cols].astype("category")

df_filled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   battery_power                  200 non-null    float64
 1   microprocessor_handling_speed  200 non-null    float64
 2   megapixels_front_cam           200 non-null    float64
 3   int_memory                     200 non-null    float64
 4   mobile_depth                   200 non-null    float64
 5   mobile_wt                      200 non-null    float64
 6   n_cores                        200 non-null    float64
 7   megapixels_primary_cam         200 non-null    float64
 8   px_height                      200 non-null    float64
 9   px_width                       200 non-null    float64
 10  ram_memory                     200 non-null    float64
 11  sc_height                      200 non-null    float64
 12  sc_width                       200 non-null    float64
 13  longest_charging_time          200 non-null    float64
 14  do_have_bluetooth              200 non-null    float64
 15  do_have_dual_sim               200 non-null    float64
 16  do_have_four_g                 200 non-null    float64
 17  do_have_three_g                200 non-null    float64
 18  do_have_touch_screen           200 non-null    float64
 19  do_have_wifi                   200 non-null    float64
 20  price_range                    200 non-null    category
dtypes: category(1), float64(20)
memory usage: 31.8 KB

Check duplicates

In [19]:
all(df_filled.duplicated() == False)

True

Khong co duplicates

Luu du lieu lai

In [20]:
file_path = "../artifacts/data_correction/test_data.pkl"
myfuncs.save_python_object(file_path, df_filled)